export const GET_BURGERS_REQUEST = 'GET_BURGERS_REQUEST';
export const GET_BURGERS_SUCCESS = 'GET_BURGERS_SUCCESS';
export const GET_BURGERS_FAILED = 'GET_BURGERS_FAILED';

export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAILED = 'PLACE_ORDER_FAILED';

export const GET_USER_ORDER_REQUEST = 'GET_USER_ORDER_REQUEST';
export const GET_USER_ORDER_SUCCESS = 'GET_USER_ORDER_SUCCESS';
export const GET_USER_ORDER_FAILED = 'GET_USER_ORDER_FAILED';

export const GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST';
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS';
export const GET_ALL_ORDERS_FAILED = 'GET_ALL_ORDERS_FAILED';

export const ADD_BURGER_REQUEST = 'ADD_BURGER_REQUEST';
export const ADD_BURGER_SUCCESS = 'ADD_BURGER_SUCCESS';
export const ADD_BURGER_FAILED = 'ADD_BURGER_FAILED';

export const UPDATE_BURGER_REQUEST = 'UPDATE_BURGER_REQUEST';
export const UPDATE_BURGER_SUCCESS = 'UPDATE_BURGER_SUCCESS';
export const UPDATE_BURGER_FAILED = 'UPDATE_BURGER_FAILED';

export const GET_BURGERS_BY_ID_REQUEST = 'GET_BURGERS_BY_ID_REQUEST';
export const GET_BURGERS_BY_ID_SUCCESS = 'GET_BURGERS_BY_ID_SUCCESS';
export const GET_BURGERS_BY_ID_FAILED = 'GET_BURGERS_BY_ID_FAILED';


